analysis/urls.py
from django.urls import path
from . import views

app_name = 'analysis'

urlpatterns = [
    path('', views.Index.as_view(), name='index'),
    path('get_news/', views.GetNews.as_view(), name='get_news')
]

score_analysis/urls.py
from django.contrib import admin
from django.urls import path, include
from analysis import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('student/', include('student.urls')),
    path('', include('analysis.urls')),
]

handler404 = views.page_not_found

student/urls.py
from django.urls import path
from . import views

app_name = 'student'

urlpatterns = [
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
    path('personal/', views.Personal.as_view(), name='personal'),
    path('personal/info', views.StudentInfo.as_view(), name='info'),
    path('personal/score', views.ScoreInfo.as_view(), name='score'),
    path('personal/gpa', views.GPA.as_view(), name='gpa'),
    path('personal/charts', views.Charts.as_view(), name='charts'),
    path('personal/exportExcel', views.ExportExcel.as_view(), name='export_excel'),
]

student/models.py
from django.db import models

from werkzeug.security import generate_password_hash, check_password_hash


class User(models.Model):
    username = models.CharField(max_length=11, verbose_name='用户名', unique=True)
    _password = models.CharField(max_length=128, verbose_name='密码')
    mg_key = models.CharField(max_length=12, verbose_name='数据键')

    @property
    def password(self):
        return self._password

    @password.setter
    def password(self, pwd):
        self._password = generate_password_hash(pwd)

    def check_password(self, pwd):
        return check_password_hash(self._password, pwd)

    def __str__(self):
        return self.username

    class Meta:
        db_table = 'user'

student/views.py
import json
from io import BytesIO

import xlwt
from django.conf import settings
from django.http import JsonResponse, HttpResponse
from django.shortcuts import render, reverse, redirect
from django.views.generic.base import View
from pymongo import MongoClient

from celery_tasks.tasks import get_jg_score, get_bjg_score, get_sx_score
from utils.charts import json_response, charts
from utils.tools import get_point
from spider.spider import get_cookies, get_info
from process.process import process_info

from .models import User


class Login(View):
    """学生登录"""
    client = MongoClient(settings.MG_HOST, settings.MG_PORT)

    def get(self, request):
        return render(request, 'student/login.html')

    def post(self, request):
        username = request.POST.get('username')
        password = request.POST.get('password')
        try:
            user = User.objects.get(username=username)
            request.session['username'] = user.username
            return JsonResponse({'status': True, 'url': reverse('student:personal')})
        except User.DoesNotExist:
            cookies = get_cookies(username, password)
            if not cookies:
                return JsonResponse({'status': False, 'msg': '登录失败!'})
        key = 'u' + username
        user = User.objects.create(username=username, password=password, mg_key=key)
        jg = list(self.client.jg[user.mg_key].find({"学期": {"$regex": '学期.*'}}))
        bjg = list(self.client.bjg[user.mg_key].find({"类型": {"$regex": ".*bjg"}}))
        sx = list(self.client.sx[user.mg_key].find({"类型": {"$regex": "sx.*"}}))
        if not jg:
            get_jg_score.delay(user.username, cookies)
        if not bjg:
            get_bjg_score.delay(user.username, cookies)
        if not sx:
            get_sx_score.delay(user.username, cookies)
        request.session['cookies'] = cookies
        request.session['username'] = user.username
        return JsonResponse({'status': True, 'url': reverse('student:personal')})


class Logout(View):
    """退出"""

    def get(self, request):
        if not request.session.get('username'):
            return redirect('student:login')
        request.session.flush()
        return redirect('analysis:index')


class Personal(View):
    """欢迎界面"""

    def get(self, request):
        return render(request, 'student/welcome.html')


class StudentInfo(View):
    """个人信息"""

    def get(self, request):
        context = {
            'base_info': dict(),
            'school_info': dict(),
            'graduation_info': dict()
        }
        info_url = settings.INFO_URL
        cookies = request.session.get('cookies')
        info_text = get_info(info_url, cookies)
        if not info_text:
            return render(request, 'student/info.html', context=context)
        results = process_info(info_text)
        if not results:
            return render(request, 'student/info.html', context=context)
        context = {
            'base_info': results[0],
            'school_info': results[1],
            'graduation_info': results[2]
        }
        return render(request, 'student/info.html', context=context)


class ScoreInfo(View):
    """获取学生成绩"""
    client = MongoClient(settings.MG_HOST, settings.MG_PORT)

    def get(self, request):
        info_type = request.GET.get('oper')
        if info_type == 'bjg':
            db = self.client.bjg
            collection = 'u' + request.session.get('username')
            cbjg_list = db[collection].find({'类型': 'cbjg'})
            sbjg_list = db[collection].find({'类型': 'sbjg'})
            return render(request, 'student/bjg_tables.html', {'cbjg_list': list(cbjg_list),
                                                               'sbjg_list': list(sbjg_list)})
        if info_type == 'sx':
            db = self.client.sx
            collection = 'u' + request.session.get('username')
            bx_list = db[collection].find({'类型': 'sx_bx'})
            xx_list = db[collection].find({'类型': 'sx_xx'})
            rx_list = db[collection].find({'类型': 'sx_rx'})
            return render(request, 'student/sx_tables.html', {'bx_list': list(bx_list),
                                                              'xx_list': list(xx_list),
                                                              'rx_list': list(rx_list)})
        if info_type == 'qb':
            db = self.client.jg
            collection = 'u' + request.session.get('username')
            terms = db[collection].aggregate([{'$group': {'_id': '$学期'}}])
            term_list = list()
            total_list = list()
            for i in range(0, len(list(terms)) - 1):
                result = db[collection].find({'学期': '学期_' + str(i)})
                total = db[collection].find({'学期统计': '学期' + str(i)})
                term_list.append(list(result))
                total_list.append(list(total)[0])
            return render(request, 'student/qb_tables.html', {'term_list': term_list,
                                                              'total_list': total_list})


class GPA(View):
    """绩点查询"""
    client = MongoClient(settings.MG_HOST, settings.MG_PORT)

    def get(self, request):
        key = 'u' + request.session.get('username')
        school = request.GET.get('mode')
        result = get_point(key, self.client, school)
        if school is None:
            return render(
                request, 'student/gpa.html',
                {'current_point': result['error_message'] if isinstance(result, dict) else result}
            )
        return JsonResponse({'status': True, 'point': result})


class Charts(View):
    """图表分析"""

    def get(self, request):

        return render(request, 'student/charts.html')

    def post(self, request):
        key = 'u' + request.session.get('username')
        return json_response(json.loads(charts(key)))


class ExportExcel(View):
    """导出Excel表"""
    client = MongoClient(settings.MG_HOST, settings.MG_PORT)

    def get(self, request):
        # key = 'u' + '1509044144'
        key = 'u' + request.session.get('username')
        school = request.GET.get('mode')
        point = get_point(key, self.client, school)

        jg_score = list(self.client.jg[key].find({'学期': {'$regex': '学期.*'}}))  # 查询及格成绩
        bjg_score = list(self.client.bjg[key].find({'类型': 'sbjg'}))  # 查询尚不及格成绩
        if not jg_score:
            return JsonResponse({'status': False, 'msg': '暂无数据可进行导出!'})
        jg_score.extend(bjg_score)

        # 设置HTTPResponse的类型
        response = HttpResponse(content_type='application/vnd.ms-excel')
        response['Content-Disposition'] = 'attachment;filename=report.xls'
        # 创建一个文件对象
        wb = xlwt.Workbook(encoding='utf8')
        # 创建一个sheet对象
        sheet = wb.add_sheet('report-sheet')

        # 实线边框
        borders = xlwt.Borders()
        borders.left = xlwt.Borders.THIN
        borders.right = xlwt.Borders.THIN
        borders.top = xlwt.Borders.THIN
        borders.bottom = xlwt.Borders.THIN

        # 设置文件头的样式
        hfont = xlwt.Font()
        hfont.name = '宋体'
        hfont.height = 20*14
        style = xlwt.XFStyle()
        style.font = hfont
        style.borders = borders

        # 设置成绩信息样式
        bfont = xlwt.Font()
        bfont.name = '宋体'
        bfont.height = 20*14
        bstyle = xlwt.XFStyle()
        bstyle.font = bfont
        bstyle.borders = borders

        # 设置统计信息样式
        afont = xlwt.Font()
        afont.name = '宋体'
        afont.height = 20*14
        afont.colour_index = 2
        astyle = xlwt.XFStyle()
        astyle.font = afont
        astyle.borders = borders
        # 写入文件标题
        sheet.write(0, 0, '课程名称', style)
        sheet.write(0, 1, '成绩', style)
        sheet.write(0, 2, '学分', style)

        # 写入数据
        data_row = 1
        total = 0
        for i in jg_score:
            total += float(i['学分'])
            sheet.write(data_row, 0, i['课程名'], bstyle)
            sheet.write(data_row, 1, i['成绩'], bstyle)
            sheet.write(data_row, 2, i['学分'], bstyle)
            data_row = data_row + 1
        sheet.write(data_row, 0, '已获得总学分数(Total Credit)', astyle)
        sheet.write(data_row, 1, total, astyle)
        sheet.write(data_row + 1, 0, '平均学分绩点(General Point Average)', astyle)
        sheet.write(data_row + 1, 1, point, astyle)
        # 设置单元格宽度
        sheet.col(0).width = 18000
        sheet.col(1).width = 4000
        sheet.col(2).width = 4000

        # 写出到IO
        output = BytesIO()
        wb.save(output)
        # 重新定位到开始
        output.seek(0)
        response.write(output.getvalue())
        return response

templates/student/bjg_tables.html
{% extends 'student/tables.html' %}

{% block title %}
    <title>个人信息</title>
{% endblock %}

{% block content %}
    <div class="col-lg-12">
            <div id="dataTable_filter" class="dataTables_filter" style="text-align: right">
                搜索：<label>
                <input type="search" class="form-control form-control-sm"
                       placeholder="" aria-controls="dataTable">
                </label>
            </div>
        </div>
    <div class="row">
        <div class="col-lg-6 mb-4">
            <div class="card">
                <div class="card-header">
                    <h6 class="text-uppercase mb-0">尚不及格成绩</h6>
                </div>
                <div class="card-body">
                    <table class="table table-striped table-hover card-text">
                        <thead>
                            <tr>
                                <th>课程号</th>
                                <th>课序号</th>
                                <th>课程名</th>
                                <th>英文课程名</th>
                                <th>学分</th>
                                <th>课程属性</th>
                                <th>成绩</th>
                                <th>考试时间</th>
                                <th>未通过原因</th>
                            </tr>
                        </thead>
                        {% for k in sbjg_list %}
                            <tr>
                                <td>{{ k.课程号 }}</td>
                                <td>{{ k.课序号 }}</td>
                                <td>{{ k.课程名 }}</td>
                                <td>{{ k.英文课程名 }}</td>
                                <td>{{ k.学分 }}</td>
                                <td>{{ k.课程属性 }}</td>
                                <td>{{ k.成绩 }}</td>
                                <td>{{ k.考试时间 }}</td>
                                <td>{{ k.未通过原因 }}</td>
                            </tr>
                            {% if total_sbjg %}
                                <tr><td colspan="9">{{ total_sbjg.0.统计 }}</td></tr>
                            {% endif %}
                        {% empty %}
                            <tr align="center">
                                <td colspan="9"><span style="font-weight: bolder">暂无数据</span></td>
                            </tr>
                        {% endfor %}
                    </table>
                </div>
            </div>
        </div>
        <div class="col-lg-6 mb-4">
            <div class="card">
                <div class="card-header">
                    <h6 class="text-uppercase mb-0">曾不及格成绩</h6>
                </div>
                <div class="card-body">
                    <table class="table table-striped table-hover card-text">
                        <thead>
                            <tr>
                                <th>课程号</th>
                                <th>课序号</th>
                                <th>课程名</th>
                                <th>英文课程名</th>
                                <th>学分</th>
                                <th>课程属性</th>
                                <th>成绩</th>
                                <th>考试时间</th>
                                <th>未通过原因</th>
                            </tr>
                        </thead>
                        {% for c in cbjg_list %}
                            <tr>
                                <td>{{ c.课程号 }}</td>
                                <td>{{ c.课序号 }}</td>
                                <td>{{ c.课程名 }}</td>
                                <td>{{ c.英文课程名 }}</td>
                                <td>{{ c.学分 }}</td>
                                <td>{{ c.课程属性 }}</td>
                                <td>{{ c.成绩 }}</td>
                                <td>{{ c.考试时间 }}</td>
                                <td>{{ c.未通过原因 }}</td>
                            </tr>
                            {% if total_cbjg %}
                                <tr><td colspan="9">{{ total_cbjg.0.统计 }}</td></tr>
                            {% endif %}
                        {% empty %}
                            <tr align="center">
                                <td colspan="9"><span style="font-weight: bolder">暂无数据</span></td>
                            </tr>
                        {% endfor %}
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block js %}
    <script type="text/javascript">
            tr = $('tbody > tr');
        function filter_tr() {
            let key = $(this).val();
            tr.each(function () {
                $(this).css('display', 'table-row')
            });
            tr.removeClass('showed');
            tr.show();
            tr.children('td:contains("'+key+'")').parent().addClass('showed');
            tr.each(function () {
                if(!$(this).hasClass('showed')){
                    $(this).css('display', 'none')
                }
            });
        }
        let search_input = $('input[type=search]');
        search_input.bind("input propertychange",filter_tr);
        $('span:contains("成绩查询")').parent().addClass('active')
            .parent().siblings().children('a').removeClass('active');
    </script>
{% endblock %}

templates/student/charts.html
{% extends 'student/tables.html' %}
{% load static %}

{% block title %}
    <meta charset="UTF-8">
    <title>图表分析</title>
    <script src="https://cdn.bootcss.com/jquery/3.0.0/jquery.min.js"></script>
    <script type="text/javascript" src="{% static 'js/charts.js' %}"></script>
{% endblock %}

{% block content %}
    <div id="bar" style="width:1000px; height:600px;">
    </div>
    <script>
        var chart = echarts.init(document.getElementById('bar'), 'white', {renderer: 'canvas'});

        $(
            function () {
                getData(chart);
            }
        );

        function getData() {
            $.ajax({
                type: "POST",
                url: "{% url 'student:charts' %}",
                data: {"csrfmiddlewaretoken": "{{ csrf_token }}"},
                dataType: 'json',
                success: function (result) {
                    chart.setOption(result.data);
                }
            });
        }
    </script>
{% endblock %}

{% block js %}
    <script>
        $('span:contains("图表分析")').parent().addClass('active')
            .parent().siblings().children('a').removeClass('active');
    </script>
{% endblock %}

templates/student/info.html
{% extends 'student/tables.html' %}

{% block title %}
    <title>个人信息</title>
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-lg-6 mb-4">
            <div class="card">
                <div class="card-header">
                    <h6 class="text-uppercase mb-0">基本信息</h6>
                </div>
                <div class="card-body">
                    <table class="table table-striped table-hover card-text">
                        {% for k, v in base_info.items %}
                            <tr>
                                <td>{{ k }}</td>
                                <td>{{ v }}</td>
                            </tr>
                        {% empty %}
                            <tr align="center">
                                <td colspan="4"><span style="font-weight: bolder">获取信息失败</span></td>
                            </tr>
                        {% endfor %}
                    </table>
                </div>
            </div>
        </div>
        <div class="col-lg-6 mb-4">
            <div class="card">
                <div class="card-header">
                    <h6 class="text-uppercase mb-0">在校信息</h6>
                </div>
                <div class="card-body">
                    <table class="table table-striped table-hover card-text">
                        {% for k, v in school_info.items %}
                            <tr>
                                <td>{{ k }}</td>
                                <td>{{ v }}</td>
                            </tr>
                        {% empty %}
                            <tr align="center">
                                <td colspan="4"><span style="font-weight: bolder">获取信息失败</span></td>
                            </tr>
                        {% endfor %}
                    </table>
                </div>
            </div>
        </div>
        <div class="col-lg-6 mb-4">
            <div class="card">
                <div class="card-header">
                    <h6 class="text-uppercase mb-0">毕业信息</h6>
                </div>
                <div class="card-body">
                    <table class="table table-striped table-hover card-text">
                        {% for k, v in graduation_info.items %}
                            <tr>
                                <td>{{ k }}</td>
                                <td>{{ v }}</td>
                            </tr>
                        {% empty %}
                            <tr align="center">
                                <td colspan="4"><span style="font-weight: bolder">获取信息失败</span></td>
                            </tr>
                        {% endfor %}
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block js %}
    <script type="text/javascript">
        $('span:contains("个人信息")').parent().addClass('active')
            .parent().siblings().children('a').removeClass('active');
    </script>
{% endblock %}

templates/student/login.html
{% load static %}
<!DOCTYPE html>
<html lang="zh">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>学生登录</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="robots" content="all,follow">
    <!-- Bootstrap CSS-->
    <link rel="stylesheet" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}">
    <!-- Font Awesome CSS-->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css"
          integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
    <!-- orion icons-->
    <link rel="stylesheet" href="{% static 'css/orionicons.css' %}">
    <!-- theme stylesheet-->
    <link rel="stylesheet" href="{% static 'css/style.default.css' %}" id="theme-stylesheet">
    <!-- Custom stylesheet - for your changes-->
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <!-- Favicon-->
    <link rel="shortcut icon" href="{% static 'img/favicon.png' %}?3">
    <style>
        .error-message {
            display: none;
        }
    </style>
</head>
<body>
<div class="page-holder d-flex align-items-center">
    <div class="container">
        <div class="row align-items-center py-5">
            <div class="col-5 col-lg-7 mx-auto mb-5 mb-lg-0">
                <div class="pr-lg-5"><img src="{% static 'img/illustration.svg' %}" alt="" class="img-fluid"></div>
            </div>
            <div class="col-lg-5 px-lg-4">
                <h1 class="text-base text-primary text-uppercase mb-4">中北大学成绩分析系统</h1>
                <h2 class="mb-4">欢迎回来!</h2>
                <p class="text-muted">真正的英雄主义，是在看清生活的真相后，依然热爱生活。</p>
                <p class="text-muted"> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;--
                    罗曼·罗兰</p>
                <form id="loginForm" action="#" onsubmit="return false;" class="mt-4">
                    <div class="form-group mb-4">
                        <input type="text" name="username" placeholder="学号"
                               class="form-control border-0 shadow form-control-lg">
                    </div>
                    <div class="form-group mb-4">
                        <input type="password" name="password" placeholder="密码"
                               class="form-control border-0 shadow form-control-lg text-violet">
                    </div>
                    <div class="form-group mb-4">
                        <h6 align="center" class="text-danger error-message">账号或密码错误!</h6>
                    </div>
                    <div class="form-group mb-4">
                        <div class="custom-control custom-checkbox">
                            <input id="customCheck1" type="checkbox" checked class="custom-control-input">
                            <label for="customCheck1" class="custom-control-label">记住我</label>
                        </div>
                    </div>
                    <button style="margin-left: 50px" type="submit" class="btn btn-primary shadow px-5">登录</button>
                    <button style="margin-left: 85px" type="button" class="btn btn-primary shadow px-5">返回</button>
                </form>
            </div>
        </div>
        <p class="mt-5 mb-0 text-gray-400 text-center">
            Copyright &copy; 2019.成绩分析系统
            & 中北大学
        </p>
    </div>
</div>

<!-- JavaScript files-->
<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'vendor/popper.js/umd/popper.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>
<script src="{% static 'vendor/jquery.cookie/jquery.cookie.js' %}"></script>
<script src="{% static 'vendor/chart.js/Chart.min.js' %}"></script>
<script src="{% static 'js/js.cookie.min.js' %}"></script>
<script src="{% static 'js/front.js' %}"></script>
<script type="text/javascript">
    sub = $('button[type=submit]');
    $('input').focus(function () {
        $('h6.error-message').css('display', 'none');
        sub.html('登录').removeAttr('disabled');
    });
    $('#loginForm').submit(function () {

        sub.html('登录中...').attr('disabled', 'true');
        let username = $('input[name=username]').val();
        let password = $('input[name=password]').val();
        if (username.length === 0 || password.length === 0) {
            $('h6.error-message').css('display', 'block').html('请将信息填写完整!');
            sub.html('登录');
            return false
        }
        if (username.length !== 10 || password.length < 6) {
            $('h6.error-message').css('display', 'block').html('用户名或密码错误!');
            sub.html('登录');
            return false
        }
        $.post(
            '{% url "student:login" %}',
            {'csrfmiddlewaretoken': '{{ csrf_token }}', 'username': username, 'password': password},
            function (result) {
                if (result['status']) {
                    window.location.href = result['url']
                } else {
                    $('h6.error-message').css('display', 'block').html(result['msg']);
                    sub.html('登录')
                }
            }
        )
    });
    $('button:contains("返回")').click(function () {
            window.location.href = '{% url "analysis:index" %}'
        })
</script>
</body>
</html>

templates/student/qb_tables.html
{% extends 'student/tables.html' %}
{% load static %}
{% block title %}
    <title>个人信息</title>
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-lg-12">
            <div id="dataTable_filter" class="dataTables_filter" style="text-align: right">
                搜索：<label>
                <input type="search" class="form-control form-control-sm"
                       placeholder="" aria-controls="dataTable">
            </label>
            </div>
        </div>
        {% for term in term_list %}
            <div class="col-lg-6 mb-5">
                <div class="card">
                    <div class="card-header">
                        {% if term.0.学期 == '学期_0' %}
                            <h6 class="text-uppercase mb-0">大一上学期</h6>
                        {% elif term.0.学期 == '学期_1' %}
                            <h6 class="text-uppercase mb-0">大一下学期</h6>
                        {% elif term.0.学期 == '学期_2' %}
                            <h6 class="text-uppercase mb-0">大二上学期</h6>
                        {% elif term.0.学期 == '学期_3' %}
                            <h6 class="text-uppercase mb-0">大二下学期</h6>
                        {% elif term.0.学期 == '学期_4' %}
                            <h6 class="text-uppercase mb-0">大三上学期</h6>
                        {% elif term.0.学期 == '学期_5' %}
                            <h6 class="text-uppercase mb-0">大三下学期</h6>
                        {% elif term.0.学期 == '学期_6' %}
                            <h6 class="text-uppercase mb-0">大四上学期</h6>
                        {% elif term.0.学期 == '学期_7' %}
                            <h6 class="text-uppercase mb-0">大四下学期</h6>
                        {% endif %}
                    </div>
                    <div class="card-body">
                        <table class="table table-striped table-hover card-text">
                            <thead>
                            <tr class="thead">
                                <th>课程号</th>
                                <th>课序号</th>
                                <th>课程名</th>
                                <th>英文课程名</th>
                                <th>学分</th>
                                <th>课程属性</th>
                                <th>成绩</th>
                            </tr>
                            </thead>
                            {% for tr in term %}
                                <tr>
                                    <td>{{ tr.课程号 }}</td>
                                    <td>{{ tr.课序号 }}</td>
                                    <td>{{ tr.课程名 }}</td>
                                    <td>{{ tr.英文课程名 }}</td>
                                    <td>{{ tr.学分 }}</td>
                                    <td>{{ tr.课程属性 }}</td>
                                    <td>{{ tr.成绩 }}</td>
                                </tr>
                            {% empty %}
                                <tr align="center">
                                    <td colspan="7"><span style="font-weight: bolder">暂无数据</span></td>
                                </tr>
                            {% endfor %}
                            <tr>
                                <td colspan="7">
                                    {% if forloop.counter0 == 0 %}
                                        {{ total_list.0.数据 }}
                                    {% elif forloop.counter0 == 1 %}
                                        {{ total_list.1.数据 }}
                                    {% elif forloop.counter0 == 2 %}
                                        {{ total_list.2.数据 }}
                                    {% elif forloop.counter0 == 3 %}
                                        {{ total_list.3.数据 }}
                                    {% elif forloop.counter0 == 4 %}
                                        {{ total_list.4.数据 }}
                                    {% elif forloop.counter0 == 5 %}
                                        {{ total_list.5.数据 }}
                                    {% elif forloop.counter0 == 6 %}
                                        {{ total_list.6.数据 }}
                                    {% elif forloop.counter0 == 7 %}
                                        {{ total_list.7.数据 }}
                                    {% endif %}
                                </td>
                            </tr>
                        </table>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

{% block js %}
    <script type="text/javascript">

        tr = $('tbody > tr');

        function filter_tr() {
            let key = $(this).val();
            tr.each(function () {
                $(this).css('display', 'table-row')
            });
            tr.removeClass('showed');
            tr.show();
            tr.children('td:contains("' + key + '")').parent().addClass('showed');
            tr.each(function () {
                if (!$(this).hasClass('showed')) {
                    $(this).css('display', 'none')
                }
            });
        }

        let search_input = $('input[type=search]');
        search_input.bind("input propertychange", filter_tr);
        $('span:contains("成绩查询")').parent().addClass('active')
            .parent().siblings().children('a').removeClass('active');
    </script>
{% endblock %}

templates/student/welcome.html
{% extends 'student/tables.html' %}

{% block title %}
    <title>个人中心</title>
{% endblock %}

{% block content %}
    <h1 align="center" style="margin-top: 20%;">欢迎使用成绩分析系统(学生)</h1>
{% endblock %}

{% block js %}
    <script type="text/javascript">
        $('span').parent().removeClass('active')
    </script>
{% endblock %}